### ISSUE TITLE
Cannot reconnect to internet after lose connection

### ISSUE THREAD

**Issue by suntus** [wanduow/wandio#6]
Sorry for my poor English first.
I use wandio to get meta information from internet. But after the connection break(e.g. unplug the network cable) I cannot get data anymore. And it stuck at here:
```
#0  pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f147122372d in thread_read (state=0x7f14600296f0, buffer=0x50f27000,
    len=1093632) at ior-thread.c:213
#2  0x00007f14712232d2 in refill_buffer (io=0x7f1460029610, len=752) at ior-peek.c:132
#3  peek_read (io=0x7f1460029610, buffer=0x4cda7056, len=752) at ior-peek.c:192
```

I don't know whether I use wandio correctly or just the feature of it.

**Comment by alistairking** [comment]
Hi @suntus. 

Can you give us some more information about how you are using wandio? 

Wandio is usually used as a library -- are you using it from within your own code? or is something else calling wandio (perhaps libtrace or bgpstream).

What type of file are you reading from -- a local file? or a file on a web server? or?

**Comment by suntus** [comment]
I saw it in bgpstream, and read from a web server. Most time the bgpstream worked well and got data correctly. Since my network break down somewhile, bgpstream will stop and can't restart.
I don't know how to overcome it. Or just monitor the network data activities of bgpstream and restart it when no coming data for a period of time?

Thx.🙂
